#!/usr/bin/env node
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const OUT = join(ROOT, 'creative', 'exports', 'media-kit-v1', 'capcut', 'luts')
mkdirSync(OUT, { recursive: true })

const profiles = [
  { id: 'overcast-grass', title: 'Overcast Grass', exposure: 1.025, contrast: 1.08, saturation: 1.12, lift: 0.006, rgb: [1.03, 1.01, 0.96] },
  { id: 'harsh-noon', title: 'Harsh Noon', exposure: 0.97, contrast: 0.92, saturation: 1.03, lift: 0.025, rgb: [1.01, 1.0, 0.98] },
  { id: 'backlit-player', title: 'Backlit Player', exposure: 1.04, contrast: 0.95, saturation: 1.06, lift: 0.045, rgb: [1.025, 1.0, 0.97] },
  { id: 'golden-hour-control', title: 'Golden Hour Control', exposure: 0.99, contrast: 1.04, saturation: 0.96, lift: 0.008, rgb: [0.99, 1.0, 1.035] },
  { id: 'flat-phone-punch', title: 'Flat Phone Punch', exposure: 1.0, contrast: 1.12, saturation: 1.04, lift: 0.002, rgb: [1.01, 1.0, 0.985] },
]

const size = 33
const clamp = (v) => Math.max(0, Math.min(1, v))

function transform([r, g, b], p) {
  let c = [r, g, b].map((v, i) => v * p.exposure * p.rgb[i])
  // Shadow-biased lift retains white volleyball panels better than a global offset.
  c = c.map((v) => v + p.lift * (1 - v) * (1 - v))
  c = c.map((v) => (v - 0.5) * p.contrast + 0.5)
  const luma = c[0] * 0.2126 + c[1] * 0.7152 + c[2] * 0.0722
  c = c.map((v) => luma + (v - luma) * p.saturation)
  // Gentle highlight shoulder avoids hard clipping after the matrix.
  c = c.map((v) => v > 0.78 ? 0.78 + (v - 0.78) * 0.86 : v)
  return c.map(clamp)
}

for (const p of profiles) {
  const lines = [
    `TITLE "Let's Pepper · ${p.title}"`,
    '# Apply at 20–40% after exposure and white-balance correction.',
    `LUT_3D_SIZE ${size}`,
    'DOMAIN_MIN 0.0 0.0 0.0',
    'DOMAIN_MAX 1.0 1.0 1.0',
  ]
  for (let bz = 0; bz < size; bz++) {
    for (let gy = 0; gy < size; gy++) {
      for (let rx = 0; rx < size; rx++) {
        const out = transform([rx / (size - 1), gy / (size - 1), bz / (size - 1)], p)
        lines.push(out.map((v) => v.toFixed(7)).join(' '))
      }
    }
  }
  const path = join(OUT, `${p.id}.cube`)
  writeFileSync(path, `${lines.join('\n')}\n`)
  console.log(`✓ ${path}`)
}

writeFileSync(join(OUT, 'README.md'), `# Let's Pepper field LUTs

These five original 33-point LUTs are restrained starting points for the recurring
outdoor conditions in the Reel corpus. Correct exposure and white balance first,
then apply a LUT at 20–40% strength. Protect faces, white ball panels, and jerseys.

They do not replace shot matching and should not be stacked with CapCut's automatic
filters. All transforms are deterministic and generated by \`build-luts.mjs\`.
`)
